name: foulandfortune
description: 14.1 Fortune Pool Scoring App
publish_to: 'none'
version: 3.8.3+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  confetti: ^0.7.0
  audioplayers: ^6.0.0
  google_fonts: ^6.3.3
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  google_generative_ai: ^0.4.7
  mailer: ^6.0.1
  video_player: ^2.10.1
  http: ^1.6.0
  wakelock_plus: ^1.2.8
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  go_router: ^14.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#2A1B0E"
  image: assets/images/app_logo.png
  fullscreen: true
  android_12:
    image: assets/images/app_logo.png
    color: "#2A1B0E"
    icon_background_color: "#2A1B0E"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/images/balls/
    - assets/images/ui/
    - assets/images/achievements/




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2A1B0E"
  adaptive_icon_foreground: "assets/icon/app_icon_safe_zone.png"

